module Servactory
  module Maintenance
    module Attributes
      module Tools
        class CheckErrors
          extend Forwardable

          @collection: Set[String]

          def initialize: (?Set[String] collection) -> void

          def not_blank: -> CheckErrors
        end
      end
    end
  end
end
