module Servactory
  module Maintenance
    module ObjectMode
      class ClassNamesCollection
        extend Forwardable

        @collection: Set[Class]

        def initialize: (Set[Class] collection) -> void
      end
    end
  end
end
