module Servactory
  module OutputArguments
    module Tools
      class Prepare
        @collection_of_output_arguments: Collection
        @context: instance

        def self.prepare: (*untyped) ?{ () -> untyped } -> void

        def initialize: (instance context, Collection collection_of_output_arguments) -> void

        def prepare: () -> void

        private

        def create_instance_variable_for: (OutputArgument output_argument) -> void

        # EXAMPLE:
        #
        #   define_method(:user=) do |value|;
        #     Servactory::InternalArguments::Checks::Type.check!( context: self, output_argument:, value: );
        #
        #     instance_variable_set(:@user, value);
        #   end;
        #
        #   private attr_reader :user;
        #
        def context_output_argument_template_for: (untyped output_argument) -> String
      end
    end
  end
end
