module Servactory
  module Configuration
    module OptionHelpers
      class OptionHelpersCollection
        include Enumerable[Maintenance::Options::Helper]

        @helpers: Hash[Symbol, Maintenance::Options::Helper]

        def initialize: (?Enumerable[Maintenance::Options::Helper] collection) -> void

        def initialize_dup: (OptionHelpersCollection original) -> void

        def each: () { (Maintenance::Options::Helper) -> void } -> self
                | () -> Enumerator[Maintenance::Options::Helper, self]

        def <<: (Maintenance::Options::Helper helper) -> self

        def merge: (Enumerable[Maintenance::Options::Helper] helpers) -> self

        def dynamic_options: -> OptionHelpersCollection

        def find_by: (name: Symbol) -> Maintenance::Options::Helper?

        def replace: (name: Symbol, with: Maintenance::Options::Helper) -> void
      end
    end
  end
end
