module Servactory
  module Maintenance
    module Attributes
      class Collection
        extend Forwardable

        @collection: Set[untyped]
        @attributes_index: Hash[Symbol, untyped]?
        @declarations_index: Hash[Symbol, untyped]?

        def initialize: (?Set[untyped] collection) -> void

        def initialize_dup: (Collection original) -> void

        def <<: (untyped attribute) -> self

        def merge: (Collection | Enumerable[untyped] other) -> self

        def names: () -> Array[Symbol]

        def only: (*Symbol names) -> Collection

        def except: (*Symbol names) -> Collection

        def find_by: (name: Symbol) -> untyped

        private

        def attributes_index: () -> Hash[Symbol, untyped]

        def declarations_index: () -> Hash[Symbol, untyped]

        def lookup_name: (untyped attribute) -> Symbol
      end
    end
  end
end
