module Servactory
  module Maintenance
    module Attributes
      class OptionHelper
        attr_reader name: Symbol

        attr_reader equivalent: Hash[Symbol, untyped]

        def initialize: (name: Symbol, equivalent: Hash[Symbol, untyped]) -> void
      end
    end
  end
end
