module Servactory
  module Maintenance
    module Attributes
      class OptionsCollection
        extend Forwardable

        @collection: Set[Option]

        def initialize: () -> void

        def names: () -> Array[Symbol]
        def validation_classes: () -> Array[Class]
        def options_for_checks: () -> Hash[Symbol, untyped]
        def defined_conflict_code: () -> untyped
        def find_by: (name: Symbol) -> untyped

        private

        def extract_normalized_body_from: (option: untyped) -> untyped
        def resolve_conflicts_from: (option: untyped) -> Array[untyped]
      end
    end
  end
end
