module Servactory
  module InputArguments
    module Tools
      class Check
        @collection_of_input_arguments: Collection
        @context: instance

        @errors: Array[String]
        @incoming_arguments: untyped

        def self.check!: (*untyped) ?{ () -> untyped } -> void

        def initialize: (instance context, untyped incoming_arguments, Collection collection_of_input_arguments) -> void

        def check!: () -> void

        private

        def process_input: (InputArgument input) -> void

        def process_option: (Symbol check_key, Hash[Symbol, untyped] check_options, input: InputArgument) -> void

        def process_check_class: (Class check_class, input: InputArgument, check_key: Symbol, check_options: Hash[Symbol, untyped]) -> instance

        def check_classes: () -> ::Array[Class]

        def raise_errors: () -> void
      end
    end
  end
end
