module Servactory
  module ToolKit
    module DynamicOptions
      class Base
        @option_name: Symbol

        def initialize: (Symbol option_name) -> void

        def setup: (Symbol name) -> Maintenance::Attributes::OptionHelper

        def equivalent_with: (Symbol name) -> Proc

        def must_content_with: (untyped received_value) -> Hash[Symbol, untyped]
      end
    end
  end
end
