module Servactory
  module ToolKit
    module DynamicOptions
      class Format < Must
        FORMATS: Hash[Symbol, untyped]

        def self.setup: (?::Symbol option_name) -> untyped

        def common_condition_with: (value: untyped, option: Must::WorkOption, **untyped `**`) -> ::Array[Symbol | bool]
      end
    end
  end
end
