module Servactory
  module ToolKit
    module DynamicOptions
      class Min < Must
        def self.setup: (?::Symbol option_name) -> Maintenance::Attributes::OptionHelper
      end
    end
  end
end
