module Servactory
  module ToolKit
    module DynamicOptions
      class MultipleOf < Must
        def self.use: (?::Symbol option_name) -> Servactory::Maintenance::Attributes::OptionHelper

        def condition_for_input_with: (**untyped _options) -> (::Array[Hash[Symbol, untyped] | Symbol | bool] | bool)
        def condition_for_internal_with: (**untyped _options) -> (::Array[Hash[Symbol, untyped] | Symbol | bool] | bool)
        def condition_for_output_with: (**untyped _options) -> (::Array[Hash[Symbol, untyped] | Symbol | bool] | bool)

        def common_condition_with: (value: Numeric, option: WorkOption, **untyped) -> bool

        def message_for_input_with: (service: Servactory::Context::Workspace, input: Servactory::Inputs::Input, value: Numeric, option_name: Symbol, option_value: untyped, **untyped) -> String
        def message_for_internal_with: (service: Servactory::Context::Workspace, internal: Servactory::Internals::Internal, value: Numeric, option_name: Symbol, option_value: untyped, **untyped) -> String
        def message_for_output_with: (service: Servactory::Context::Workspace, output: Servactory::Outputs::Output, value: Numeric, option_name: Symbol, option_value: untyped, **untyped) -> String
      end
    end
  end
end
