module Servactory
  module ToolKit
    module DynamicOptions
      class MultipleOf < Must
        def self.use: (?::Symbol option_name) -> Maintenance::Attributes::OptionHelper

        def common_condition_with: (value: untyped, option: Must::WorkOption, **untyped `**`) -> bool
      end
    end
  end
end
