module Servactory
  module ToolKit
    module DynamicOptions
      class Must
        class WorkOption
          attr_reader name: Symbol
          attr_reader value: untyped
          attr_reader message: (Proc? | String?)
          attr_reader properties: Hash[Symbol, untyped]
        end

        @option_name: Symbol
        @body_key: Symbol
        @body_fallback: Symbol?

        def initialize: (Symbol option_name, ?Symbol body_key) -> void

        def must: (Symbol option_name) -> Servactory::Maintenance::Attributes::OptionHelper

        def equivalent_with: (Symbol name) -> Proc

        def must_content_with: (WorkOption option) -> Hash[Symbol, untyped]

        def must_content_value_with: (WorkOption option) -> Proc

        def must_content_message_with: (WorkOption option) -> Proc

        def condition_for_input_with: (**untyped _options) -> (::Array[Hash[Symbol, untyped] | Symbol | bool] | bool)

        def condition_for_internal_with: (**untyped _options) -> (::Array[Hash[Symbol, untyped] | Symbol | bool] | bool)

        def condition_for_output_with: (**untyped _options) -> (::Array[Hash[Symbol, untyped] | Symbol | bool] | bool)

        def message_for_input_with: (**untyped _options) -> String

        def message_for_internal_with: (**untyped _options) -> String

        def message_for_output_with: (**untyped _options) -> String
      end
    end
  end
end
