module Servactory
  module InputArguments
    class DefineInputMethod
      attr_reader name: Symbol

      attr_reader content: Proc

      def initialize: (name: Symbol, content: Proc) -> void
    end
  end
end
