module Servactory
  module InputArguments
    module DSL
      def self.included: (untyped base) -> untyped

      module ClassMethods
        @collection_of_input_arguments: Collection

        @input_arguments_workbench: Workbench

        private

        def input: (Symbol name, **un options) -> void

        def collection_of_input_arguments: () -> Collection

        def input_arguments_workbench: () -> Workbench
      end
    end
  end
end
