module Servactory
  module InputArguments
    class OptionsCollection
      # NOTE: http://words.steveklabnik.com/beware-subclassing-ruby-core-classes
      extend Forwardable

      @collection: Set[Option]

      def initialize: (*untyped) -> void

      def check_classes: () -> OptionsCollection

      def defined_conflicts: -> String

      def options_for_checks: -> Hash[Symbol, untyped]
    end
  end
end
