module Servactory
  module Inputs
    class Collection < Servactory::Maintenance::Attributes::Collection
      @collection: Set[Input]

      def find_by: (name: Symbol) -> Input?

      private

      def lookup_name: (Input attribute) -> Symbol
    end
  end
end
