module Servactory
  module Inputs
    class Collection < Servactory::Attributes::Collection
      @collection: Set[Input]

      def find_by: (name: Symbol) -> Input?

      private

      def lookup_name: (Input item) -> Symbol
    end
  end
end
