module Servactory
  module Inputs
    module DSL
      def self.included: (untyped base) -> void

      module ClassMethods
        @collection_of_inputs: Collection

        attr_reader config: Servactory::Configuration::Setup

        def inherited: (untyped child) -> void

        private

        def input: (Symbol name, *Symbol helpers, **untyped options) -> void

        def collection_of_inputs: () -> Collection
      end
    end
  end
end
