module Servactory
  module Inputs
    class IncomingArguments
      @config: Configuration::Setup

      @arguments: Hash[Symbol, untyped]

      attr_reader arguments: Hash[Symbol, untyped]

      def initialize: (Configuration::Setup config, **Hash[Symbol, untyped] arguments) -> void

      def names: () -> Array[Symbol]

      def fetch: (Symbol name, untyped default_value) -> untyped

      def assign: (untyped key, untyped value) -> untyped

      def method_missing: (Symbol name, *untyped args) { (?) -> untyped } -> untyped

      def respond_to_missing?: (Symbol name, *untyped) -> untyped
    end
  end
end
