module Servactory
  module Inputs
    class Input
      ARRAY_DEFAULT_VALUE: ^(is: bool, message: Proc | String | nil) -> { is: bool, message: String | nil }

      @collection_of_options: OptionsCollection

      attr_reader name: Symbol
      attr_reader internal_name: Symbol?
      attr_reader option_helpers: OptionHelpersCollection

      def initialize: (
        Symbol name,
        *Symbol helpers,
        as: Symbol?,
        type: (Class | Array[Class]),
        **untyped options
      ) -> void

      def method_missing: (Symbol name, *untyped args) { () -> untyped } -> void

      def respond_to_missing?: (Symbol name, *untyped) -> void

      def apply_helpers_for_options: (helpers: Array[Symbol], options: Hash[Symbol, untyped]) -> Hash[Symbol, untyped]

      def add_basic_options_with: (type: (Class | Array[Class]), options: untyped) -> void

      def add_required_option_with: (untyped options) -> OptionsCollection

      def add_types_option_with: ((Class | Array[Class]) type) -> OptionsCollection

      def add_default_option_with: (untyped options) -> OptionsCollection

      def add_array_option_with: (untyped options) -> OptionsCollection

      def add_inclusion_option_with: (untyped options) -> OptionsCollection

      def add_must_option_with: (untyped options) -> OptionsCollection

      def add_prepare_option_with: (untyped options) -> OptionsCollection

      def add_internal_option_with: (untyped options) -> OptionsCollection

      def collection_of_options: -> OptionsCollection

      def options_for_checks: () -> Hash[Symbol, untyped]

      def conflict_code: -> (Symbol | nil)

      def with_conflicts?: -> bool
    end
  end
end
