module Servactory
  module Inputs
    class Input < Servactory::Maintenance::Attributes::Base
      class Actor
        attr_reader name: Symbol
        attr_reader internal_name: Symbol
        attr_reader types: Array[Class]
        attr_reader default: untyped
        attr_reader options: Hash[Symbol, untyped]

        @attribute: Input

        def initialize: (Input input) -> void

        def system_name: () -> Symbol

        def i18n_name: () -> String

        def optional?: () -> bool

        def required?: () -> bool

        def input?: () -> bool

        def internal?: () -> bool

        def output?: () -> bool
      end

      attr_reader internal_name: Symbol

      def initialize: (
          Symbol name,
          *untyped helpers,
          ?as: Symbol?,
          option_helpers: Configuration::OptionHelpers::OptionHelpersCollection,
          **untyped options
        ) -> void

      def conflict_code: () -> untyped

      def with_conflicts?: () -> bool

      def input?: () -> bool

      private

      def available_feature_options: () -> Hash[Symbol, bool]
    end
  end
end
