module Servactory
  module Inputs
    class OptionsCollection
      # NOTE: http://words.steveklabnik.com/beware-subclassing-ruby-core-classes
      extend Forwardable

      @collection: Set[Option]

      def initialize: (*untyped) -> void

      def validation_classes: () -> Array[Class]

      def defined_conflict_code: -> Symbol

      def options_for_checks: -> Hash[Symbol, untyped]
    end
  end
end
