module Servactory
  module Inputs
    class OptionHelpersCollection
      extend Forwardable

      @collection: Set[OptionHelper]

      def initialize: (Set[OptionHelper] collection) -> void

      def find_by: (name: Symbol) -> OptionHelper?
    end
  end
end
