module ServiceFactory
  module OutputArguments
    module DSL
      def self.included: (untyped base) -> untyped

      module ClassMethods
        @collection_of_output_arguments: Collection

        @output_arguments_workbench: Workbench

        private

        def output: (Symbol name, **untyped options) -> void

        def collection_of_output_arguments: () -> Collection

        def output_arguments_workbench: () -> Workbench
      end
    end
  end
end
