module ServiceFactory
  module OutputArguments
    class OutputArgument
      attr_reader name: Symbol

      attr_reader types: Array[Class]

      attr_reader required: bool

      attr_reader default: untyped

      def initialize: (Symbol name, type: Class, **untyped options) -> void

      def options_for_checks: () -> { types: Array[Class], required: bool, default: untyped }

      def required?: () -> bool

      def optional?: () -> bool

      def default_value_present?: () -> bool
    end
  end
end
