module Servactory
  module Inputs
    module Validations
      class Base
        attr_reader errors: Errors

        def initialize: () -> void

        def add_error: (message: (String | Proc), **untyped attributes) -> Errors
      end
    end
  end
end
