module Servactory
  module Inputs
    module Validations
      class Inclusion < Base
        DEFAULT_MESSAGE: ^(service_class_name: String, input: Input, value: untyped) -> String

        @context: instance
        @input: Input

        def self.check: (context: instance, attribute: Input, check_key: Symbol, **untyped _) -> void

        def self.should_be_checked_for?: (Input input, Symbol check_key) -> bool

        def initialize: (context: instance, input: Input) -> void

        def check: () -> void

        private

        def add_error_with: (String? message) -> void
      end
    end
  end
end
