module Servactory
  module Inputs
    module Validations
      class Required
        extend Maintenance::Validations::Concerns::ErrorBuilder

        def self.check: (
          context: untyped,
          attribute: Input,
          value: untyped,
          check_key: Symbol,
          **untyped
        ) -> String?

        def self.should_be_checked_for?: (Input input, Symbol check_key) -> bool

        private

        def self.build_error_message: (
          context: untyped,
          input: Input,
          value: untyped
        ) -> String
      end
    end
  end
end
