module Servactory
  module Inputs
    module Validations
      class Type < Base
        @context: instance
        @input: Input
        @prepared_value: String

        def self.check: (context: instance, input: Input, check_key: Symbol, **untyped) -> void

        def self.should_be_checked_for?: (Input input, Symbol check_key) -> bool

        def initialize: (context: instance, input: Input) -> void

        def check: () -> void

        private

        def prepared_value: () -> String
      end
    end
  end
end
