module Servactory
  module Inputs
    module Validations
      class Base
        def initialize: () -> void

        attr_reader errors: Errors

        def add_error: (String | Proc message, **untyped attributes) -> Errors
      end
    end
  end
end
