module Servactory
  module Inputs
    module Validations
      class Type < Base
        DEFAULT_MESSAGE: ^(service_class_name: String, input: Input, key_name: Symbol, expected_type: String, given_type: String) -> String

        @context: instance
        @input: Input
        @prepared_types: Array[Class]
        @prepared_value: String

        def self.check: (context: instance, input: Input, check_key: Symbol, **untyped) -> void

        def self.should_be_checked_for?: (Input input, Symbol check_key) -> bool

        def initialize: (context: instance, input: Input) -> void

        def check: () -> void

        private

        def prepared_types: -> Array[Class]

        def prepared_value: () -> String

        def add_default_object_error_with: (Hash[Symbol, untyped] error) -> void

        def add_default_error: -> void
      end
    end
  end
end
