module Servactory
  module Actions
    class Collection
      extend Forwardable

      @collection: Set[Action]

      def initialize: (Set[Action] collection) -> void

      def sorted_by_position: -> Collection
    end
  end
end
