module Servactory
  module Actions
    class Collection
      extend Forwardable

      @collection: (Set[Action] | Array[Action])

      def initialize: (?Enumerable[Action] collection) -> void

      def sorted_by_position: -> Collection

      def <<: (Action value) -> self
      def each: () { (Action) -> void } -> self
              | () -> Enumerator[Action]
      def sort_by: () { (Action) -> untyped } -> Array[Action]

      private

      attr_reader :collection
    end
  end
end
