module Servactory
  module Actions
    class Collection
      extend Forwardable

      @collection: Set[Action]
      @sorted: Collection?

      def initialize: (?Set[Action] collection) -> void

      def <<: (Action action) -> Set[Action]

      def each: () { (Action) -> void } -> Set[Action]

      def to_h: () -> Hash[untyped, untyped]

      def sort_by: () { (Action) -> Integer } -> Array[Action]

      def size: () -> Integer

      def empty?: () -> bool

      def sorted_by_position: () -> Collection
    end
  end
end
