module Servactory
  module Actions
    class MethodCollection
      extend Forwardable

      @collection: Set[Action]

      def initialize: (Set[Action] collection) -> void

      def sorted_by_position: -> MethodCollection
    end
  end
end
