module Servactory
  module Configuration
    module CollectionMode
      class ClassNamesCollection
        extend Forwardable

        @collection: Set[Class]

        def initialize: (Set[Class] collection) -> void

        def merge: (Enumerable[Class] other) -> self
        def intersect?: (Enumerable[Class] other) -> bool
      end
    end
  end
end
