module Servactory
  module Configuration
    module CollectionMode
      class ClassNamesCollection
        extend Forwardable

        @collection: Set[Class]

        def initialize: (Set[Class] collection) -> void

        def initialize_dup: (ClassNamesCollection original) -> void
      end
    end
  end
end
