module Servactory
  module Actions
    module Shortcuts
      class Collection
        extend Forwardable

        @collection: Set[Symbol]

        def initialize: (*untyped) -> void
      end
    end
  end
end
