module Servactory
  module Context
    module Callable
      def call!: (?Hash[Symbol, untyped] arguments) -> Result
      def call: (?Hash[Symbol, untyped] arguments) -> Result

      private

      def _call!: (
        instance context,
        incoming_arguments: Hash[Symbol, untyped],
        collection_of_inputs: Inputs::Collection,
        collection_of_internals: Internals::Collection,
        collection_of_outputs: Outputs::Collection,
        collection_of_stages: Actions::Stages::Collection
      ) -> void
    end
  end
end
