module Servactory
  module Context
    class Configuration
      def input_attribute_error_class: (Errors::InputError input_attribute_error_class) -> Errors::InputError

      def output_attribute_error_class: (Errors::OutputError output_attribute_error_class) -> Errors::OutputError

      def internal_attribute_error_class: (Errors::InternalAttributeError internal_attribute_error_class) -> Errors::InternalAttributeError

      def failure_class: (Errors::Failure failure_class) -> Errors::Failure
    end
  end
end
