module Servactory
  module Context
    module DSL
      def self.included: (untyped base) -> untyped

      module Configurable
        private

        def configuration: () { () -> void } -> void
      end
    end
  end
end
