module Servactory
  module Context
    class Store
      @context: instance

      @internals: Hash[Symbol, untyped]

      @outputs: Hash[Symbol, untyped]

      @context_data: Hash[Symbol, untyped]

      @context_id: String

      def initialize: (instance context) -> void

      def outputs: () -> Hash[Symbol, untyped]

      def fetch_internal: (Symbol key) -> untyped

      def assign_internal: (Symbol key, untyped value) -> untyped

      def fetch_output: (Symbol key) -> untyped

      def assign_output: (Symbol key, untyped value) -> untyped

      private

      def internals: () -> Hash[Symbol, untyped]

      def context_data: () -> Hash[Symbol, untyped]

      def state: () -> Hash[String, Hash[Symbol, untyped]]

      def context_id: () -> String
    end
  end
end
