module Servactory
  module Context
    module Workspace
      @errors: Array[Errors::Error]

      attr_reader inputs: InputArguments

      def initialize: () -> void

      def assign_inputs: (InputArguments inputs) -> untyped

      def errors: -> Array[Errors::Error]

      def fail_input!: (Symbol input_attribute_name, String message) -> untyped

      def fail!: (String error) -> Array[Errors::Error]

      def raise_first_error: () -> (nil | untyped)
    end
  end
end
