module Servactory
  module Context
    module Workspace
      class Actor
        attr_reader class_name: String

        @i18n_root_key: String

        def initialize: (instance context) -> void

        def translate: (String key, **untyped options) -> String
      end

      @inputs: Inputs
      @internals: Internals
      @outputs: Outputs
      @servactory_service_warehouse: Context::Warehouse::Setup

      attr_reader collection_of_inputs: Inputs::Collection
      attr_reader collection_of_internals: Internals::Collection
      attr_reader collection_of_outputs: Outputs::Collection

      def inputs: -> Inputs
      alias inp inputs

      def internals: -> Internals
      alias int internals

      def outputs: -> Outputs
      alias out outputs

      def initialize: () -> void

      def success!: () -> Exception

      def fail_input!: (Symbol input_name, message: String, meta: untyped?) -> Exception

      def fail_internal!: (Symbol internal_name, message: String, meta: untyped?) -> Exception

      def fail_output!: (Symbol output_name, message: String, meta: untyped?) -> Exception

      def fail!: (Symbol type, message: String, meta: untyped?) -> Exception

      def fail_result!: (Result service_result) -> Exception

      private

      @servactory_service_info: Actor

      def _call!: (
        incoming_arguments: Hash[Symbol, untyped],
        collection_of_inputs: Inputs::Collection,
        collection_of_internals: Internals::Collection,
        collection_of_outputs: Outputs::Collection,
        collection_of_stages: Actions::Stages::Collection
      ) -> void

      def call!: (
        collection_of_inputs: Inputs::Collection,
        collection_of_internals: Internals::Collection,
        collection_of_outputs: Outputs::Collection,
        ** untyped
      ) -> void

      def call: -> Exception

      def servactory_service_info: -> Actor

      def servactory_service_warehouse: -> Warehouse::Setup
    end
  end
end
