module Servactory
  module Exceptions
    class Failure < Base
      attr_reader type: Symbol?
      attr_reader message: String
      attr_reader meta: untyped?

      def initialize: (type: Symbol?, message: String, meta: untyped?) -> void

      def normalize_method_name: (Symbol name) -> Symbol
    end
  end
end
