module Servactory
  module Exceptions
    class Internal < Base
      attr_reader service: Context::Workspace::Actor
      attr_reader message: String
      attr_reader internal_name: Symbol?
      attr_reader meta: untyped?

      def initialize: (context: instance, message: String, internal_name: Symbol?, meta: untyped?) -> void
    end
  end
end
