module Servactory
  module Exceptions
    class Output < Base
      attr_reader service: Servactory::Context::Workspace::Actor
      attr_reader message: String
      attr_reader output_name: Symbol?
      attr_reader meta: untyped?

      def initialize: (
        context: Servactory::Context::Workspace,
        message: String,
        ?output_name: Symbol?,
        ?meta: untyped?
      ) -> void

      private

      # API: Datory
      attr_reader context: Servactory::Context::Workspace
    end
  end
end
