module Servactory
  module Exceptions
    class Success < Base
      attr_reader context: Servactory::Context::Workspace

      def initialize: (context: Servactory::Context::Workspace) -> void
    end
  end
end
