module Servactory
  module TestKit
    module Rspec
      module Helpers
        class MockExecutor
          @service_class: Class
          @configs: Array[ServiceMockConfig]
          @rspec_context: untyped

          def initialize: (service_class: Class, configs: Array[ServiceMockConfig], rspec_context: untyped) -> void

          def execute: (?untyped message_expectation) -> untyped

          def update_arguments: (untyped message_expectation) -> untyped

          private

          def sequential?: () -> bool
          def stub_or_update_arguments: (untyped message_expectation) -> untyped
          def argument_matcher: () -> untyped
          def apply_sequential_behavior: (untyped message_expectation) -> void
          def all_returns?: () -> bool
          def build_callable: (ServiceMockConfig config) -> ^(*untyped) -> untyped
          def apply_return_behavior: (untyped message_expectation, ServiceMockConfig config) -> void
          def wrap_with_keyword_inputs: (Proc wrap_block) -> Proc
          def validate_configs!: () -> void
        end
      end
    end
  end
end
