module Servactory
  module TestKit
    module Rspec
      module Helpers
        class MockExecutor
          class Stub < ::Data
            attr_reader message_expectation: untyped
            attr_reader inputs_guard: ServiceInputsGuard

            def self.new: (message_expectation: untyped, inputs_guard: ServiceInputsGuard) -> instance
                        | (untyped message_expectation, ServiceInputsGuard inputs_guard) -> instance
          end

          CALL_ORIGINAL: Proc

          @service_class: Class
          @configs: Array[ServiceMockConfig]
          @rspec_context: untyped

          def initialize: (service_class: Class, configs: Array[ServiceMockConfig], rspec_context: untyped) -> void

          def execute: (?Stub? stub) -> Stub

          def update_arguments: (Stub stub) -> Stub

          private

          def sequential?: () -> bool
          def register_stub: () -> Stub
          def method_type: () -> Symbol
          def argument_matcher: () -> untyped
          def apply_sequential_behavior: (untyped message_expectation) -> void
          def all_returns?: () -> bool
          def build_callable: (ServiceMockConfig config) -> ^(*untyped) -> untyped
          def apply_return_behavior: (Stub stub, ServiceMockConfig config) -> void
          def build_pass_through: (ServiceInputsGuard inputs_guard, ServiceMockConfig config) -> Proc
          def wrap_with_keyword_inputs: (Proc wrap_block) -> Proc
          def validate_configs!: () -> void
        end
      end
    end
  end
end
