module Servactory
  module Stroma
    module Settings
      class Collection
        extend Forwardable

        @storage: Hash[Symbol, RegistrySettings]

        def initialize: (?Hash[Symbol, RegistrySettings] storage) -> void

        def initialize_dup: (Collection original) -> void

        def []: (Symbol | String registry_key) -> RegistrySettings

        def each: () { (Symbol, RegistrySettings) -> void } -> Hash[Symbol, RegistrySettings]

        def map: [T] () { (Symbol, RegistrySettings) -> T } -> Array[T]

        def keys: () -> Array[Symbol]

        def size: () -> Integer

        def empty?: () -> bool

        def to_h: () -> Hash[Symbol, Hash[Symbol, Hash[Symbol, untyped]]]
      end
    end
  end
end
