module Servactory
  module Stroma
    module Settings
      class Setting
        extend Forwardable

        @data: Hash[Symbol, untyped]

        def initialize: (?Hash[Symbol, untyped] data) -> void

        def initialize_dup: (Setting original) -> void

        def []: (Symbol key) -> untyped

        def []=: (Symbol key, untyped value) -> untyped

        def key?: (Symbol key) -> bool

        def keys: () -> Array[Symbol]

        def each: () { (Symbol, untyped) -> void } -> Hash[Symbol, untyped]

        def map: [T] () { (Symbol, untyped) -> T } -> Array[T]

        def empty?: () -> bool

        def size: () -> Integer

        def to_h: () -> Hash[Symbol, untyped]

        def fetch: (Symbol key, ?untyped default) ?{ () -> untyped } -> untyped

        private

        def deep_dup: (untyped obj) -> untyped
      end
    end
  end
end
