module ServiceFactory
  module OutputArguments
    module Tools
      class Conflicts
        @collection_of_output_arguments: Collection
        @@collection_of_internal_arguments: InternalArguments::Collection
        @context: instance
        @overlapping_attributes: Array[Symbol]

        def self.check!: (*untyped) ?{ () -> untyped } -> void

        def initialize: (instance context, Collection collection_of_output_arguments, InternalArguments::Collection collection_of_internal_arguments) -> void

        def check!: () -> void

        private

        def overlapping_attributes: () -> Array[Symbol]
      end
    end
  end
end
