module Servactory
  module OutputArguments
    module Checks
      class Type < Base
        DEFAULT_MESSAGE: Proc

        @context: instance

        @output_argument: OutputArgument
        @prepared_types: Array[Class]
        @value: untyped

        def self.check!: (*untyped) ?{ () -> untyped } -> void

        def initialize: (context: instance, output_argument: OutputArgument, value: untyped) -> void

        def check!: () -> void

        private

        def prepared_types: -> Array[Class]
      end
    end
  end
end
