module Servactory
  module Context
    module Workspace
      class Errors
        # NOTE: http://words.steveklabnik.com/beware-subclassing-ruby-core-classes
        extend Forwardable

        @collection: Set[Error]

        def initialize: (?Set[Error] collection) -> void

        def not_blank: () -> Errors

        def for_fails: () -> Errors

        def for_inputs: () -> Errors
      end
    end
  end
end
