module Servactory
  module Context
    module Workspace
      class Error
        attr_reader type: Symbol

        attr_reader message: String

        attr_reader attribute_name: Symbol?

        def initialize: (type: Symbol, message: String, ?attribute_name: Symbol?) -> void
      end
    end
  end
end
