module Servactory
  module Context
    module Workspace
      class Inputs
        @context: instance
        @collection_of_inputs: Inputs::Collection

        def initialize: (context: instance, collection_of_inputs: Inputs::Collection) -> void

        def only: (Symbol input_names) -> Hash[Symbol, untyped]

        def except: (Symbol input_names) -> Hash[Symbol, untyped]

        def method_missing: (Symbol name, *untyped args) { () -> untyped } -> void

        def respond_to_missing?: (Symbol name, *untyped) -> void

        private

        def getter_with: (name: Symbol) { () -> untyped } -> void
      end
    end
  end
end
