module Servactory
  module Context
    module Workspace
      class Inputs
        @context: instance
        @collection_of_inputs: Servactory::Inputs::Collection
        @incoming_arguments: untyped

        def initialize: (Workspace context, workbench: Servactory::Inputs::Workbench) -> void

        def method_missing: (Symbol name, *untyped args) { () -> untyped } -> void

        def respond_to_missing?: (Symbol name, *untyped) -> void

        private

        def getter_with: (name: Symbol) { () -> untyped } -> void
      end
    end
  end
end
