module Servactory
  module Context
    module Workspace
      class Internals
        @context: instance
        @collection_of_internals: Internals::Collection
        @validated_attributes: Set[Symbol]

        def initialize: (context: instance, collection_of_internals: Internals::Collection) -> void

        def only: (*Symbol internal_names) -> Hash[Symbol, untyped]

        def except: (*Symbol internal_names) -> Hash[Symbol, untyped]

        def method_missing: (Symbol name, *untyped args) -> void

        def respond_to_missing?: (Symbol name, *untyped) -> bool

        private

        def validated_attributes: () -> Set[Symbol]

        def assign_with: (prepared_name: Symbol, value: untyped?) { () -> untyped } -> void

        def fetch_with: (name: Symbol) { () -> untyped } -> untyped

        def fetch_value: (attribute: untyped) -> untyped

        def resolve_internal: (Symbol name) -> bool

        def raise_error_for: (Symbol type, Symbol name) -> bot
      end
    end
  end
end
