module Servactory
  module Maintenance
    module Validations
      module Concerns
        module ErrorBuilder
          def process_message: ((String | Proc) message, **untyped attributes) -> String
        end
      end
    end
  end
end
