# frozen_string_literal: true

module Servactory
  module TestKit
    module Rspec
      module Matchers
        module Concerns
          # Concern for recognizing must rules generated by option helpers.
          #
          # ## Purpose
          #
          # Option helpers expand into `must` rules: dynamic options such as
          # `format`, `min`, `max`, `multiple_of` and `target`, subclasses of
          # `Servactory::ToolKit::DynamicOptions::Must`, and custom helpers
          # registered with `*_option_helpers`. The messages of these rules
          # depend on the validated value, so they cannot be checked before
          # the service runs.
          #
          # ## Detection
          #
          # A rule is generated by an option helper when:
          # - its condition was built by a `DynamicOptions::Must` instance, or
          # - it is a rule of a helper registered for the attribute type,
          #   compared by equality and by the source location of its condition
          #
          # ## Usage
          #
          # ```ruby
          # class MustSubmatcher < Base::Submatcher
          #   include Concerns::OptionHelperRules
          #
          #   def initialize(context, names)
          #     super(context)
          #     raise ArgumentError if names.any? { |name| option_helper_rule?(name) }
          #   end
          # end
          # ```
          module OptionHelperRules
            # Includes InstanceMethods in the including class.
            #
            # @param base [Class] The class including this concern
            # @return [void]
            def self.included(base)
              base.include(InstanceMethods)
            end

            # Instance methods added by this concern.
            module InstanceMethods
              # Checks whether a must rule of the attribute was generated by an option helper.
              #
              # @param name [Symbol] The rule name
              # @return [Boolean] True if an option helper generated the rule
              def option_helper_rule?(name)
                rule = (attribute_data[:must] || {})[name]
                return false if rule.nil?

                dynamic_option_rule?(rule) || option_helper_rules.any? { |helper_rule| same_rule?(helper_rule, rule) }
              end

              private

              # Returns the condition of a rule in advanced or simple mode.
              #
              # @param rule [Hash, Proc] The rule
              # @return [Object] The condition
              def rule_condition(rule)
                rule.is_a?(Hash) ? rule[:is] : rule
              end

              # Checks whether a `DynamicOptions::Must` instance built the rule's condition.
              #
              # @param rule [Hash, Proc] The rule
              # @return [Boolean] True for rules of dynamic options
              def dynamic_option_rule?(rule)
                condition = rule_condition(rule)
                return false unless condition.is_a?(Proc)

                condition.binding.receiver.is_a?(Servactory::ToolKit::DynamicOptions::Must)
              rescue StandardError
                false
              end

              # Compares a rule with a rule generated by an option helper.
              #
              # @param helper_rule [Hash, Proc] The rule generated by an option helper
              # @param rule [Hash, Proc] The attribute's rule
              # @return [Boolean] True if both are the same rule
              def same_rule?(helper_rule, rule)
                return true if helper_rule == rule

                location = condition_location(rule)
                !location.nil? && location == condition_location(helper_rule)
              end

              # Returns the source location of a rule's condition.
              #
              # @param rule [Hash, Proc] The rule
              # @return [Array(String, Integer), nil] The source location
              def condition_location(rule)
                condition = rule_condition(rule)
                condition.source_location if condition.is_a?(Proc)
              end

              # Returns the must rules of the option helpers registered for the attribute type.
              #
              # @return [Array<Hash, Proc>] Rules generated by option helpers
              def option_helper_rules
                @option_helper_rules ||=
                  described_class.config.public_send(:"#{attribute_type}_option_helpers").flat_map do |helper|
                    rules = helper_option(helper)
                    rules.is_a?(Hash) && rules[:must].is_a?(Hash) ? rules[:must].values : []
                  end
              end

              # Expands an option helper the way the library does for the attribute.
              #
              # @param helper [Servactory::Maintenance::Options::Helper] The option helper
              # @return [Object] The options the helper expands into
              def helper_option(helper)
                return helper.equivalent unless helper.equivalent.is_a?(Proc)

                values = attribute_data.fetch(:actor).options[helper.name].deep_dup
                values.is_a?(Hash) ? helper.equivalent.call(**values) : helper.equivalent.call(values)
              rescue StandardError
                nil
              end
            end
          end
        end
      end
    end
  end
end
