module Servactory
  module Internals
    class Collection < Servactory::Maintenance::Attributes::Collection
      @collection: Set[Internal]

      def find_by: (name: Symbol) -> Internal?
    end
  end
end
