module Servactory
  module Internals
    class Collection
      # NOTE: http://words.steveklabnik.com/beware-subclassing-ruby-core-classes
      extend Forwardable

      @collection: Set[Internal]

      def initialize: (Set[Internal] collection) -> void

      def only: (Array[Symbol] internal_names) -> Collection

      def names: () -> Array[Symbol]

      def find_by: (name: Symbol) -> Internal?
    end
  end
end
