module Servactory
  module Internals
    module DSL
      def self.included: (untyped base) -> untyped

      module ClassMethods
        @collection_of_internals: Collection

        def inherited: -> void

        private

        def internal: (Symbol name, **untyped options) -> void

        def collection_of_internals: () -> Collection
      end
    end
  end
end
