module Servactory
  module Internals
    module DSL
      def self.included: (untyped base) -> void

      module ClassMethods
        @collection_of_internals: Collection

        attr_reader config: Servactory::Configuration::Setup

        def inherited: (untyped child) -> void

        private

        def internal: (Symbol name, *Symbol helpers, **untyped options) -> void

        def collection_of_internals: () -> Collection
      end
    end
  end
end
