module Servactory
  module Internals
    class Internal
      attr_reader name: Symbol
      attr_reader collection_mode_class_names: Maintenance::CollectionMode::ClassNamesCollection
      attr_reader hash_mode_class_names: Maintenance::HashMode::ClassNamesCollection
      attr_reader collection_of_options: Maintenance::Attributes::OptionsCollection

      def initialize: (
        Symbol name,
        collection_mode_class_names: Maintenance::CollectionMode::ClassNamesCollection,
        hash_mode_class_names: Maintenance::HashMode::ClassNamesCollection,
        **untyped options
      ) -> void

      def method_missing: (Symbol name, *untyped args) { () -> untyped } -> void

      def respond_to_missing?: (Symbol name, *untyped) -> void

      def register_options: (helpers: Array[Symbol], options: Hash[Symbol, untyped]) -> Maintenance::Attributes::OptionsCollection

      def options_for_checks: () -> Hash[Symbol, untyped]

      def system_name: -> Symbol

      def i18n_name: -> String

      def input?: -> bool

      def internal?: -> bool

      def output?: -> bool
    end
  end
end
