module Servactory
  module Internals
    class Internal < Servactory::Attributes::Base
      class Actor
        attr_reader name: Symbol
        attr_reader types: Array[untyped]
        attr_reader options: Hash[Symbol, untyped]

        @attribute: Internal

        def initialize: (Internal internal) -> void

        def system_name: () -> Symbol

        def i18n_name: () -> String

        def input?: () -> false

        def internal?: () -> true

        def output?: () -> false
      end

      def internal?: () -> true

      private

      def available_feature_options: () -> Hash[Symbol, bool]
    end
  end
end
