module Servactory
  module Internals
    class Workbench
      attr_reader collection: Collection

      def self.work_with: (*untyped) ?{ () -> untyped } -> untyped

      def initialize: (Collection collection) -> void

      def assign: (context: instance) -> void

      private

      attr_reader context: instance
    end
  end
end
