module Servactory
  module InternalArguments
    class Workbench
      def self.work_with: (*untyped) ?{ () -> untyped } -> untyped

      def initialize: (Collection collection_of_internal_arguments) -> void

      def assign: (context: instance) -> void

      def prepare: () -> void

      private

      attr_reader context: instance

      attr_reader collection_of_internal_arguments: Collection
    end
  end
end
