module Servactory
  module Actions
    module Stages
      class Collection
        extend Forwardable

        @collection: Set[Stage]
        @sorted_by_position: Collection?

        def initialize: (?Set[Stage] collection) -> void

        def <<: (Stage stage) -> Set[Stage]

        def each: () { (Stage) -> void } -> Set[Stage]

        def merge: (Set[Stage] | Collection) -> Set[Stage]

        def to_h: () -> Hash[untyped, untyped]

        def sort_by: () { (Stage) -> Integer } -> Array[Stage]

        def size: () -> Integer

        def empty?: () -> bool

        def sorted_by_position: () -> Collection
      end
    end
  end
end
