module Servactory
  module Actions
    module Stages
      class Collection
        extend Forwardable

        @collection: Set[Stage]

        def initialize: (?Enumerable[Stage] collection) -> void

        def <<: (Stage) -> self
        def each: () { (Stage) -> void } -> self
                | () -> Enumerator[Stage]
        def merge: (Enumerable[Stage] other) -> self
        def sort_by: () { (Stage) -> untyped } -> Array[Stage]
        def size: () -> Integer
        def empty?: () -> bool

        def sorted_by_position: () -> Collection
      end
    end
  end
end
