module Servactory
  module Actions
    module Stages
      class Stage
        attr_accessor position: Integer

        attr_accessor wrapper: Proc?

        attr_accessor rollback: Symbol?

        attr_accessor condition: (bool | Proc)?

        attr_accessor is_condition_opposite: bool

        @methods: MethodCollection

        def initialize: (
          position: Integer,
          ?wrapper: Proc?,
          ?rollback: Symbol?,
          ?condition: (bool | Proc)?,
        ) -> void

        def next_method_position: () -> Integer

        def methods: () -> MethodCollection
      end
    end
  end
end
