module Servactory
  module Stroma
    module Hooks
      class Collection
        extend Forwardable

        @collection: Set[Hook]

        def initialize: (?Set[Hook] collection) -> void

        def initialize_dup: (Collection original) -> void

        def add: (Symbol type, Symbol target_key, Module extension) -> Set[Hook]

        def before: (Symbol key) -> Array[Hook]

        def after: (Symbol key) -> Array[Hook]

        def each: () { (Hook) -> void } -> Set[Hook]

        def map: [T] () { (Hook) -> T } -> Array[T]

        def empty?: () -> bool

        def size: () -> Integer
      end
    end
  end
end
