module Servactory
  module Stroma
    module Hooks
      class Factory
        @hooks: Collection

        def initialize: (Collection hooks) -> void

        def before: (Symbol key, *Module extensions) -> void

        def after: (Symbol key, *Module extensions) -> void

        private

        def validate_key!: (Symbol key) -> void
      end
    end
  end
end
