module Servactory
  module Stroma
    module Hooks
      VALID_HOOK_TYPES: Array[Symbol]

      class Hook < Data
        attr_reader type: Symbol
        attr_reader target_key: Symbol
        attr_reader extension: Module

        def initialize: (type: Symbol, target_key: Symbol, extension: Module) -> void

        def before?: () -> bool

        def after?: () -> bool
      end
    end
  end
end
