module Servactory
  module Stage
    class Methods
      # NOTE: http://words.steveklabnik.com/beware-subclassing-ruby-core-classes
      extend Forwardable

      @methods: Set[Method]

      def initialize: (*untyped) -> void
    end
  end
end
