module Servactory
  module Stroma
    class Applier
      @target_class: Class
      @hooks: Hooks

      def initialize: (Class target_class, Hooks hooks) -> void

      def apply!: () -> void
    end
  end
end
