module Servactory
  module Stroma
    class Entry < Data
      attr_reader key: Symbol
      attr_reader extension: Module

      def self.new: (key: Symbol, extension: Module) -> Entry
    end
  end
end
