module Servactory
  module Stroma
    class Hook < Data
      VALID_TYPES: Array[Symbol]

      attr_reader type: Symbol
      attr_reader target_key: Symbol
      attr_reader extension: Module

      def initialize: (type: Symbol, target_key: Symbol, extension: Module) -> void

      def self.new: (type: Symbol, target_key: Symbol, extension: Module) -> Hook

      def before?: () -> bool
      def after?: () -> bool
    end
  end
end
