module Servactory
  module Stroma
    class Hook < Data
      attr_reader type: Symbol
      attr_reader target_key: Symbol
      attr_reader extension: Module

      def self.new: (type: Symbol, target_key: Symbol, extension: Module) -> Hook

      def before?: () -> bool
      def after?: () -> bool
    end
  end
end
