module Servactory
  module Stroma
    class Registry
      include Singleton

      @entries: Array[Entry]
      @keys_index: Hash[Symbol, Entry]
      @finalized: bool

      def self.register: (Symbol key, Module extension) -> void
      def self.finalize!: () -> void
      def self.entries: () -> Array[Entry]
      def self.keys: () -> Array[Symbol]
      def self.key?: (Symbol key) -> bool

      def initialize: () -> void

      def register: (Symbol key, Module extension) -> void

      def finalize!: () -> void

      def entries: () -> Array[Entry]

      def keys: () -> Array[Symbol]

      def key?: (Symbol key) -> bool

      private

      def ensure_finalized!: () -> void
    end
  end
end
