module Servactory
  module Stroma
    class State
      attr_reader hooks: Hooks::Collection
      attr_reader settings: Settings::Collection

      def initialize: () -> void

      def initialize_dup: (State original) -> void
    end
  end
end
