module Servactory
  module Internals
    module Validations
      class Type < Base
        DEFAULT_MESSAGE: ^(service_class_name: String, internal: Internal, value: any, object_name: Symbol, expected_type: String, given_type: String) -> Proc

        @context: instance
        @internal: Internal
        @prepared_types: Array[Class]
        @value: any

        def self.validate!: (*untyped) ?{ () -> untyped } -> void

        def should_be_checked?: -> bool

        def initialize: (context: instance, internal: Internal, value: any) -> void

        def validate!: () -> void

        private

        def prepared_types: -> Array[Class]

        def prepared_types_from: (Array[Class] types) -> Array[Class]
      end
    end
  end
end
