module Servactory
  module TestKit
    module Rspec
      module Matchers
        module Submatchers
          module Shared
            class InclusionSubmatcher < Base::Submatcher
              OPTION_NAME: Symbol

              OPTION_BODY_KEY: Symbol

              @values: Array[untyped]
              @actual_values: Array[untyped]
              @attribute_inclusion: untyped
              @attribute_inclusion_in: untyped

              def initialize: (Base::SubmatcherContext context, Array[untyped] values) -> void

              def description: () -> String

              private

              attr_reader values: Array[untyped]

              def passes?: () -> bool

              def build_failure_message: () -> String

              def attribute_inclusion: () -> untyped

              def attribute_inclusion_in: () -> untyped
            end
          end
        end
      end
    end
  end
end
