module Servactory
  module TestKit
    module Rspec
      module Matchers
        module Submatchers
          module Shared
            class MustSubmatcher < Base::Submatcher
              @must_names: Array[Symbol]
              @message_expectations: Hash[Symbol, Base::MessageExpectation]
              @actual_must_names: Array[Symbol]
              @message_mismatches: Hash[Symbol, String]
              @service_info: untyped

              def self.arguments_from: (Array[untyped] args) -> [Array[Symbol], Hash[Symbol, untyped]]

              def initialize: (Base::SubmatcherContext context, Array[Symbol] must_names, ?Hash[Symbol, untyped] message_expectations) -> void

              def description: () -> String

              private

              attr_reader must_names: Array[Symbol]

              attr_reader message_expectations: Hash[Symbol, Base::MessageExpectation]

              def passes?: () -> bool

              def build_failure_message: () -> String

              def rule_description: (Symbol name) -> String

              def attribute_must: () -> Hash[Symbol, untyped]

              def actual_must_names: () -> Array[Symbol]

              def names_match?: () -> bool

              def names_failure_message: () -> String

              def find_message_mismatches: () -> Hash[Symbol, String]

              def rule_message: (untyped rule) -> (String | Proc)?

              def call_message: (Proc message, code: Symbol) -> untyped

              def service_info: () -> untyped
            end
          end
        end
      end
    end
  end
end
