module Servactory
  module TestKit
    module Rspec
      module Matchers
        module Submatchers
          module Shared
            class SchemaSubmatcher < Base::Submatcher
              OPTION_NAME: Symbol

              OPTION_BODY_KEY: Symbol

              @schema_data: Hash[Symbol, untyped]
              @actual_schema: Hash[Symbol, untyped]

              def initialize: (Base::SubmatcherContext context, Hash[Symbol, untyped] schema_data) -> void

              def description: () -> String

              protected

              def passes?: () -> bool

              def build_failure_message: () -> String

              private

              attr_reader schema_data: Hash[Symbol, untyped]
            end
          end
        end
      end
    end
  end
end
