module Servactory
  module TestKit
    module Rspec
      module Matchers
        module Submatchers
          module Shared
            class TargetSubmatcher < Base::Submatcher
              OPTION_BODY_KEY: Symbol

              @option_name: Symbol
              @values: Array[untyped]
              @actual_values: Array[untyped]
              @attribute_target: untyped
              @attribute_target_in: untyped

              def initialize: (Base::SubmatcherContext context, Symbol option_name, Array[untyped] values) -> void

              def description: () -> String

              private

              attr_reader option_name: Symbol

              attr_reader values: Array[untyped]

              def passes?: () -> bool

              def build_failure_message: () -> String

              def formatted_values: () -> String

              def attribute_target: () -> untyped

              def attribute_target_in: () -> untyped

              def normalize_to_array: (untyped value) -> Array[untyped]
            end
          end
        end
      end
    end
  end
end
