module Servactory
  module MakeMethods
    class MakeMethod
      attr_reader name: Symbol

      attr_reader condition: (Proc | bool)?

      def initialize: (Symbol name, **untyped options) -> void
    end
  end
end
