module InputAttributeHelper
  def prepare_input_text_for: (
    check_name: Symbol,
    name: Symbol,
    service_class_name: Class,
    custom_message: String?,
    collection: bool,
    collection_message: String?,
    expected_type: Class?,
    given_type: Class?
  ) -> String

  def raise_input_error_for: (
    check_name: Symbol,
    name: Symbol,
    service_class_name: Class,
    custom_message: String?,
    collection: bool,
    collection_message: String?,
    expected_type: Class?,
    given_type: Class?
  ) -> void

  private

  def prepare_input_required_check_text_for: (name: Symbol, service_class_name: Class, custom_message: String?) -> String

  def prepare_input_type_check_text_for: (
    name: Symbol,
    service_class_name: Class,
    collection: bool,
    collection_message: String?,
    expected_type: Class,
    given_type: Class
  ) -> String
end
