module Servactory
  module Maintenance
    module Attributes
      module Validations
        class Must
          extend Concerns::ErrorBuilder

          def self.check: (
            context: untyped,
            attribute: (Inputs::Input | Internals::Internal | Outputs::Output),
            value: untyped,
            check_key: Symbol,
            check_options: Hash[Symbol, untyped]
          ) -> String?

          def self.should_be_checked_for?: (
            (Inputs::Input | Internals::Internal | Outputs::Output) attribute,
            Symbol check_key
          ) -> bool

          private

          def self.validate_condition: (
            context: untyped,
            attribute: (Inputs::Input | Internals::Internal | Outputs::Output),
            value: untyped,
            code: Symbol,
            options: Hash[Symbol, untyped]
          ) -> String?

          def self.call_check: (
            context: untyped,
            attribute: (Inputs::Input | Internals::Internal | Outputs::Output),
            value: untyped,
            check: Proc,
            code: Symbol
          ) -> Array[untyped]

          def self.build_error_message: (
            context: untyped,
            attribute: (Inputs::Input | Internals::Internal | Outputs::Output),
            value: untyped,
            code: Symbol,
            reason: Symbol?,
            meta: Hash[Symbol, untyped]?,
            message: (String | Proc)?
          ) -> String

          def self.build_syntax_error_message: (
            context: untyped,
            attribute: (Inputs::Input | Internals::Internal | Outputs::Output),
            value: untyped,
            code: Symbol,
            exception_message: String
          ) -> String
        end
      end
    end
  end
end
