module Servactory
  module Maintenance
    module Attributes
      module Validations
        class Type
          extend Concerns::ErrorBuilder

          def self.check: (
            context: untyped,
            attribute: (Inputs::Input | Internals::Internal | Outputs::Output),
            value: untyped,
            check_key: Symbol,
            **untyped
          ) -> String?

          def self.should_be_checked_for?: (
            (Inputs::Input | Internals::Internal | Outputs::Output) attribute,
            untyped value,
            Symbol check_key
          ) -> bool

          private

          def self.compute_prepared_value: (
            (Inputs::Input | Internals::Internal | Outputs::Output) attribute,
            untyped value
          ) -> untyped

          def self.build_error_message: (
            Hash[Symbol, untyped] error_data
          ) -> String
        end
      end
    end
  end
end
