module ServiceFactory
  module Stage
    class Method
      attr_reader name: Symbol

      attr_reader condition: Proc?

      def initialize: (untyped name, **untyped options) -> void
    end
  end
end
