module Servactory
  module Configuration
    module HashMode
      class ClassNamesCollection
        extend Forwardable

        @collection: Set[Class]

        def initialize: (Set[Class] collection) -> void

        def include?: (Class value) -> bool
        def intersect?: (Enumerable[Class] other) -> bool
      end
    end
  end
end
