module Servactory
  module Info
    module DSL
      def self.included: (untyped base) -> untyped

      module ClassMethods
        def info: () -> Result

        def servactory?: -> bool
      end
    end
  end
end
