module Servactory
  module TestKit
    module Rspec
      module Matchers
        module Submatchers
          module Input
            class ValidWithSubmatcher < Base::Submatcher
              include Concerns::OptionHelperRules
              include Concerns::ProcMessage
              include Concerns::RequiredMessage

              @attributes: Hash[Symbol, untyped] | Datory::Base
              @failure_reason: String?

              def initialize: (Base::SubmatcherContext context, Hash[Symbol, untyped] | Datory::Base attributes) -> void

              def description: () -> String

              private

              attr_reader attributes: Hash[Symbol, untyped] | Datory::Base

              def passes?: () -> bool

              def build_failure_message: () -> String

              def success_passes?: () -> bool

              def failure_type_passes?: () -> bool

              def type_error_message_for: (untyped value) -> String

              def default_type_error_message: (expected_type: String, given_type: String) -> String

              def failure_required_passes?: () -> bool

              def failure_optional_passes?: () -> bool

              def failure_inclusion_passes?: () -> bool

              def inclusion_error_message_for: (untyped value, untyped option_value) -> untyped

              def default_inclusion_error_message: (value: untyped, option_value: untyped) -> String

              def failure_target_passes?: () -> bool

              def target_error_message_for: (untyped value, untyped option_value) -> untyped

              def default_target_error_message: (value: untyped, option_value: untyped) -> String

              def dynamic_option_message: (untyped message, Symbol option_name, value: untyped, option_value: untyped) -> untyped

              def expect_failure_with!: (Hash[Symbol, untyped] | Datory::Base prepared_attributes, untyped expected_message) -> bool
            end
          end
        end
      end
    end
  end
end
