module Servactory
  module TestKit
    module Rspec
      module Matchers
        module Submatchers
          module Input
            class ValidWithSubmatcher < Base::Submatcher
              @attributes: Hash[Symbol, untyped]
              @failure_reason: String?

              def initialize: (Base::SubmatcherContext context, Hash[Symbol, untyped] attributes) -> void

              def description: () -> String

              private

              def passes?: () -> bool

              def build_failure_message: () -> String

              attr_reader attributes: Hash[Symbol, untyped]

              def success_passes?: () -> bool

              def failure_type_passes?: () -> bool

              def failure_required_passes?: () -> bool

              def failure_optional_passes?: () -> bool

              def failure_inclusion_passes?: () -> bool
            end
          end
        end
      end
    end
  end
end
