module Servactory
  module Generators
    class RspecGenerator < Rails::Generators::NamedBase
      @service_class: untyped
      @service_info: untyped

      def create_spec_file: () -> void

      private

      def specs_path: () -> String

      def skip_validations?: () -> bool

      def skip_pending?: () -> bool

      def call_method: () -> String

      def service_class: () -> untyped

      def service_info: () -> untyped

      def service_exists?: () -> bool

      def inputs_from_info: () -> Array[Hash[Symbol, untyped]]

      def internals_from_info: () -> Array[Hash[Symbol, untyped]]

      def outputs_from_info: () -> Array[Hash[Symbol, untyped]]

      def format_types: (Array[untyped] types) -> String

      def example_value_for_types: (Array[untyped] types) -> String
    end
  end
end
