module Servactory
  module Configuration
    module Actions
      module RescueHandlers
        class Collection
          extend Forwardable

          @collection: Set[[Class, Proc]]

          def initialize: (*untyped) -> void

          def +: (Enumerable[[Class, Proc]] other) -> Set[[Class, Proc]]
          def detect: () { ([Class, Proc] element) -> bool } -> [Class, Proc]?
          def reverse_each: () { ([Class, Proc] element) -> void } -> self
                        | () -> Enumerator[[Class, Proc]]

          def collection: () -> Array[[Class, Proc]]

          private

          attr_reader collection: Array[[Class, Proc]]
        end
      end
    end
  end
end
