module Servactory
  module Errors
    class Collection
      # NOTE: http://words.steveklabnik.com/beware-subclassing-ruby-core-classes
      extend Forwardable

      @collection: Set[Failure | InputError | InternalError | OutputError]

      def initialize: (?Set[Failure | InputError | InternalError | OutputError] collection) -> void

      def not_blank: () -> Collection

      def for_fails: () -> Collection
    end
  end
end
