module Servactory
  module Errors
    class Error
      attr_reader section: Symbol

      attr_reader message: String

      def initialize: (Symbol section, String message) -> void
    end
  end
end
