module Servactory
  module Errors
    class OutputError < Base
      attr_reader message: String
      attr_reader output_name: Symbol?
      attr_reader meta: untyped?

      def initialize: (message: String, output_name: Symbol?, meta: untyped?) -> void
    end
  end
end
