module Servactory
  module Maintenance
    module Options
      class Collection
        extend Forwardable

        @collection: Set[Option]
        @validation_classes: Array[Class]
        @options_for_checks: Hash[Symbol, untyped]
        @options_index: Hash[Symbol, Option]

        def initialize: () -> void

        def names: () -> Array[Symbol]
        def validation_classes: () -> Array[Class]
        def options_for_checks: () -> Hash[Symbol, untyped]
        def defined_conflict_code: () -> untyped
        def find_by: (name: Symbol) -> Option?

        private

        def options_index: () -> Hash[Symbol, Option]
        def extract_normalized_body_from: (option: Option) -> untyped
        def resolve_conflicts_from: (option: Option) -> Array[untyped]
      end
    end
  end
end
