module Servactory
  module Maintenance
    module Options
      class Collection
        extend Forwardable

        @collection: Set[Option]
        @validations_for_checks: Array[[Symbol, untyped, Class]]?
        @options_index: Hash[Symbol, Option]?

        def initialize: () -> void

        def initialize_dup: (Collection original) -> void
        def <<: (Option option) -> self
        def names: () -> Array[Symbol]
        def validation_classes: () -> Array[Class]
        def options_for_checks: () -> Hash[Symbol, untyped]
        def validations_for_checks: () -> Array[[Symbol, untyped, Class]]
        def defined_conflict_code: () -> Symbol?
        def find_by: (name: Symbol) -> Option?

        private

        def check_options_by_key: () -> Hash[Symbol, untyped]
        def reset_memoized_caches: () -> void
        def options_index: () -> Hash[Symbol, Option]
        def extract_normalized_body_from: (option: Option) -> untyped
      end
    end
  end
end
