module Servactory
  module Maintenance
    module Options
      class DefineMethod
        attr_reader name: Symbol

        attr_reader content: Proc

        def initialize: (name: Symbol, content: Proc) -> void
      end
    end
  end
end
