module Servactory
  module Actions
    module Tools
      class Rules
        @context: untyped

        RESERVED_METHOD_NAMES: Array[Symbol]

        def self.check!: (*untyped) ?{ () -> untyped } -> void

        def initialize: (untyped context) -> void

        def check!: () -> Exception?

        private

        def check_public_methods!: () -> Exception?

        def check_protected_methods!: () -> Exception?

        def check_private_methods!: () -> Exception?

        def check_in!: (Array[Symbol] list_of_methods) -> Exception?

        def raise_message_with!: (String formatted_text) -> Exception
      end
    end
  end
end
