module Servactory
  module Actions
    module Tools
      class Runner
        @context: instance
        @collection_of_stages: Stages::Collection

        def self.run!: (*untyped) ?{ () -> untyped } -> void

        def initialize: (instance context, Stages::Collection collection_of_stages) -> void

        def run!: () -> void

        private

        def use_call: () -> void

        def call_stage: (Stages::Stage stage) -> void

        def call_wrapper_with_methods: (Proc wrapper, Symbol? rollback, Collection methods) -> void

        def call_methods: (Collection methods) -> void

        def call_method: (Action method) -> void

        def unnecessary_for_stage?: (Stages::Stage stage) -> bool

        def unnecessary_for_make?: (Action method) -> bool

        def prepare_condition_for: ((Proc | bool)? condition) -> bool

        def rescue_no_method_error_with: (exception: Exception) -> Exception

        def rescue_name_error_with: (exception: Exception, method: Action) -> Exception
      end
    end
  end
end
