module ApplicationService
  module Extensions
    module StatusActive
      module DSL
        def self.included: (untyped base) -> untyped

        module ClassMethods
          private

          attr_accessor status_active_model_name: Class

          def status_active!: (Class model_name) -> void
        end

        module InstanceMethods
          private

          def call!: (**untyped) -> void
        end
      end
    end
  end
end
