module Servactory
  module OutputAttributes
    class Collection
      # NOTE: http://words.steveklabnik.com/beware-subclassing-ruby-core-classes
      extend Forwardable

      @collection: Set[OutputAttribute]

      def initialize: (*untyped) -> void

      def names: () -> Array[Symbol]
    end
  end
end
