module Servactory
  module OutputAttributes
    class Workbench
      def self.work_with: (*untyped) ?{ () -> untyped } -> instance

      def initialize: (Collection collection_of_output_attributes) -> void

      def assign: (context: instance) -> void

      def find_conflicts_in!: (collection_of_internal_attributes: InternalAttributes::Collection) -> void

      def prepare: () -> void

      private

      attr_reader context: instance

      attr_reader collection_of_output_attributes: Collection
    end
  end
end
