module Servactory
  module Context
    module Warehouse
      class Base
        @arguments: Hash[Symbol, untyped]

        def initialize: (?Hash[Symbol, untyped] arguments) -> void

        def fetch: (Symbol name, untyped default_value) -> untyped

        def assign: (Symbol key, untyped value) -> untyped
      end
    end
  end
end
