module Servactory
  module Context
    module Warehouse
      class Inputs < Base
        @context: untyped

        def initialize: (untyped context, ?::Hash[untyped, untyped] arguments) -> void

        def names: () -> untyped

        def merge!: (untyped arguments) -> untyped

        def method_missing: (Symbol name, *untyped _args) { () -> untyped } -> void

        def respond_to_missing?: (Symbol name, *untyped) -> void

        def raise_error_for: (untyped input_name) -> void
      end
    end
  end
end
