module Servactory
  module Context
    module Warehouse
      class Outputs < Base
        extend Forwardable

        def each_pair: () { (Symbol, untyped) -> void } -> self
                     | () -> Enumerator[[Symbol, untyped]]
      end
    end
  end
end
