module Servactory
  module Context
    module Warehouse
      class Outputs
        extend Forwardable

        @arguments: Hash[Symbol, untyped]

        def initialize: (Hash[Symbol, untyped] storage_outputs) -> void

        def each_pair: () { (Symbol, untyped) -> void } -> Hash[Symbol, untyped]

        def fetch: (Symbol name, untyped? default_value) -> untyped

        def assign: (Symbol key, untyped value) -> untyped
      end
    end
  end
end
