module Servactory
  module Context
    module Warehouse
      class Setup
        @context: untyped
        @crate: Crate
        @inputs: Inputs?
        @internals: Internals?
        @outputs: Outputs?

        def initialize: (untyped context) -> void

        def assign_inputs: (Hash[Symbol, untyped] arguments) -> Hash[Symbol, untyped]

        def fetch_input: (Symbol name) -> untyped

        def assign_internal: (Symbol name, untyped value) -> untyped

        def fetch_internal: (Symbol name) -> untyped

        def assign_output: (Symbol name, untyped value) -> untyped

        def fetch_output: (Symbol name) -> untyped

        def inputs: () -> Inputs

        def internals: () -> Internals

        def outputs: () -> Outputs
      end
    end
  end
end
