module Servactory
  class Base
    include Context::DSL

    include Inputs::DSL

    include Internals::DSL

    include Outputs::DSL

    include Actions::DSL

    def self.config: () -> Servactory::Configuration::Setup
  end
end
