module Servactory
  class Configuration
    attr_accessor input_argument_error_class: singleton(Servactory::Errors::InputArgumentError)

    attr_accessor internal_argument_error_class: singleton(Servactory::Errors::InternalArgumentError)

    attr_accessor output_argument_error_class: singleton(Servactory::Errors::OutputArgumentError)

    attr_accessor failure_class: singleton(Servactory::Errors::Failure)

    def initialize: () -> void
  end
end
