module Servactory
  module DSL
    module Extensions
      self.@registry: Array[Module]

      def self.registry: () -> Array[Module]

      def self.register: (*Module extensions) -> Array[Module]

      def self.clear: () -> Array[untyped]
    end

    def self.included: (Class base) -> void

    def self.with_extensions: (*Module extensions) -> singleton(DSL)
  end
end
