module Servactory
  module Utils
    FALSE_VALUES: Set[false | Symbol | String | Integer]

    def self?.define_attribute_with: (input: Inputs::Input, internal: Internals::Internal, output: Outputs::Output) -> (Inputs::Input | Internals::Internal | Outputs::Output | Exception)

    # @param value [#to_s]
    # @return [Boolean]
    def self?.true?: (untyped value) -> untyped

    # @param value [#to_s]
    # @return [Boolean]
    def self?.value_present?: (untyped value) -> untyped

    # NOTE: Based on `query_cast_attribute` from ActiveRecord:
    #       https://github.com/rails/rails/blob/main/activerecord/lib/active_record/attribute_methods/query.rb
    # @param value [#to_s]
    # @return [Boolean]
    def self?.query_attribute: (untyped value) -> untyped
  end
end
