module Servactory
  module Utils
    # @param data [Hash, Datory::Base]
    def self.adapt: (untyped data) -> Hash[Symbol, untyped]

    def self.fetch_hash_with_desired_attribute: (
      (Inputs::Input | Internals::Internal | Outputs::Output) attribute
    ) -> Hash[Symbol, untyped]

    def self.define_attribute_with: (
      ?input: Inputs::Input?,
      ?internal: Internals::Internal?,
      ?output: Outputs::Output?
    ) -> (Inputs::Input | Internals::Internal | Outputs::Output)

    def self.really_input?: ((Inputs::Input | Internals::Internal | Outputs::Output)? attribute) -> bool

    def self.really_internal?: ((Inputs::Input | Internals::Internal | Outputs::Output)? attribute) -> bool

    def self.really_output?: ((Inputs::Input | Internals::Internal | Outputs::Output)? attribute) -> bool

    def self.extract_special_character_from: (String string) -> [String, String?]

    FALSE_VALUES: Set[false | nil | String | Symbol | Integer]

    # @param value [#to_s]
    def self.true?: (untyped value) -> bool

    # @param value [#to_s]
    def self.value_present?: (untyped value) -> bool

    # @param value [#to_s]
    def self.query_attribute: (untyped value) -> bool

    def self.constantize_class: ((Class | String | Symbol) class_or_name) -> Class?

    private

    # @param data [Datory::Base]
    def self.instance_variables_to_hash_from: (untyped data) -> Hash[Symbol, untyped]
  end
end
