module Servactory
  module Inputs
    module Tools
      class CheckErrors
        # NOTE: http://words.steveklabnik.com/beware-subclassing-ruby-core-classes
        extend Forwardable

        @collection: Set[String]

        def initialize: (Set[String] collection) -> void

        def not_blank: -> CheckErrors
      end
    end
  end
end
