module Servactory
  module Inputs
    module Tools
      class Rules
        @collection_of_inputs: Inputs
        @context: instance

        def self.check!: (Servactory::Context::Workspace, Servactory::Inputs::Collection) -> Exception?

        def initialize: (Servactory::Context::Workspace, Servactory::Inputs::Collection) -> void

        def check!: () -> Exception?

        private

        def check_for!: (Servactory::Inputs::Input) -> void

        def raise_error_for: (Servactory::Inputs::Input) -> void
      end
    end
  end
end
