module Servactory
  module Inputs
    module Tools
      class Rules
        @context: Context::Workspace
        @collection_of_inputs: Inputs

        def self.check!: (*untyped, **untyped) ?{ (?) -> untyped } -> void

        def initialize: (Context::Workspace context, Inputs collection_of_inputs) -> void

        def check!: () -> void

        private

        def check_for!: (Input input) -> void

        def raise_exception_for: (Input input) -> void

        def exception_message_for: (Input input) -> String
      end
    end
  end
end
