module Servactory
  module Inputs
    module Tools
      class Unnecessary
        @collection_of_inputs: Collection
        @context: instance
        @unnecessary_attributes: Array[Symbol]

        def self.find!: (*untyped, **untyped) ?{ (?) -> untyped } -> void

        def initialize: (instance context, Collection collection_of_inputs) -> void

        def find!: () -> void

        private

        def unnecessary_attributes: () -> Array[Symbol]
      end
    end
  end
end
