module Servactory
  module Inputs
    module Tools
      class Unnecessary
        @collection_of_inputs: Collection
        @context: instance
        @unnecessary_attributes: Array[Symbol]

        def self.find!: (Servactory::Context::Workspace, Servactory::Inputs::Collection) -> Exception?

        def initialize: (Servactory::Context::Workspace, Servactory::Inputs::Collection) -> void

        def find!: () -> Exception?

        private

        def unnecessary_attributes: () -> Array[Symbol]
      end
    end
  end
end
