module Servactory
  module Inputs
    module Tools
      class Validation
        @context: instance
        @collection_of_inputs: Collection

        def self.validate!: (*untyped, **untyped) ?{ (?) -> untyped } -> Exception?

        def initialize: (instance context, Collection collection_of_inputs) -> void

        def validate!: () -> Exception?

        private

        @errors: Maintenance::Attributes::Tools::CheckErrors

        def process_input: (Input input) -> void

        def process_option: (Symbol check_key, Hash[Symbol, untyped] check_options, input: Input) -> void

        def process_validation_class: (validation_class: Class, input: Input, check_key: Symbol, check_options: Hash[Symbol, untyped]) -> instance

        def validation_classes_from: (Input input) -> Array[Class]

        def errors: -> Maintenance::Attributes::Tools::CheckErrors

        def raise_errors: () -> void
      end
    end
  end
end
