module Servactory
  module Inputs
    module Tools
      class Warehouse
        @context: untyped

        @incoming_arguments: untyped

        def self.assign: (Servactory::Context::Workspace, (::Hash[untyped, untyped] | ::Datory::Base)) -> Hash[Symbol, untyped]

        def initialize: (Servactory::Context::Workspace, (::Hash[untyped, untyped] | ::Datory::Base)) -> void

        def assign: () -> Hash[Symbol, untyped]

        private

        def adapted_arguments: () -> Hash[Symbol, untyped]
      end
    end
  end
end
