module Servactory
  module Methods
    class Collection
      # NOTE: http://words.steveklabnik.com/beware-subclassing-ruby-core-classes
      extend Forwardable

      @collection: Set[Collection]

      def initialize: (Set[Collection] collection) -> void

      def sorted_by_position: -> Collection

      def grouped_by_wrapper: -> Collection
    end
  end
end
