module Servactory
  module Methods
    module DSL
      def self.included: (untyped base) -> untyped

      module ClassMethods
        @collection_of_methods: Collection
        @methods_workbench: Workbench

        def inherited: -> void

        private

        def make: (Symbol name, **untyped options) -> void

        def collection_of_methods: () -> Collection

        def methods_workbench: () -> Workbench
      end
    end
  end
end
