module Servactory
  module Methods
    module DSL
      def self.included: (untyped base) -> untyped

      module ClassMethods
        @collection_of_methods: Collection
        @methods_workbench: Workbench

        def inherited: -> void

        private

        def make: (Symbol name, position: Integer?, **untyped options) -> void

        def method_missing: (Symbol, *untyped, **untyped) ?{ (*untyped, **untyped) -> untyped } -> void

        def respond_to_missing?: (Symbol shortcut_name, *untyped) -> bool

        def next_position: -> Integer

        def collection_of_methods: () -> Collection

        def methods_workbench: () -> Workbench
      end
    end
  end
end
