module Servactory
  module Methods
    class MethodCollection
      extend Forwardable

      @collection: Set[Method]

      def initialize: (Set[Method] collection) -> void

      def sorted_by_position: -> MethodCollection
    end
  end
end
