module Servactory
  module Methods
    class StageCollection
      extend Forwardable

      @collection: Set[StageCollection]

      def initialize: (Set[StageCollection] collection) -> void

      def sorted_by_position: -> StageCollection
    end
  end
end
