module Servactory
  module Methods
    class Workbench
      def self.work_with: (*untyped) ?{ () -> untyped } -> untyped

      def initialize: (StageCollection collection_of_stages) -> void

      def assign: (context: instance) -> void

      def run!: () -> void

      private

      attr_reader context: instance

      attr_reader collection_of_stages: StageCollection

      def try_to_use_call: -> void

      def call_wrapper_with_methods: (Proc wrapper, MethodCollection methods) -> void

      def call_methods: (MethodCollection methods) -> void

      def prepare_condition_for: ((Proc | bool)? condition) -> bool

      def unnecessary_for?: (Method make_method) -> bool
    end
  end
end
