module Servactory
  module Configuration
    class ClassNamesCollection
      extend Forwardable

      @collection: Set[Class]

      def initialize: (Set[Class] collection) -> void
    end
  end
end
