module Servactory
  module Configuration
    module DSL
      def self.included: (untyped base) -> untyped

      module ClassMethods
        @configuration_factory: Factory

        def inherited: (untyped child) -> void

        private

        def configuration: () { () -> untyped } -> void
      end
    end
  end
end
