module Servactory
  module Configuration
    module DSL
      def self.included: (untyped base) -> untyped

      module ClassMethods
        @config: Servactory::Configuration::Setup
        @configuration_factory: Factory

        def inherited: -> void

        def config: -> Servactory::Configuration::Setup

        private

        def configuration: () { () -> untyped } -> void
      end
    end
  end
end
