module Servactory
  module Configuration
    class Setup
      attr_accessor input_exception_class: singleton(Exceptions::Input)

      attr_accessor internal_exception_class: singleton(Exceptions::Internal)

      attr_accessor output_exception_class: singleton(Exceptions::Output)

      attr_accessor success_class: singleton(Exceptions::Success)

      attr_accessor failure_class: singleton(Exceptions::Failure)

      attr_accessor result_class: singleton(Servactory::Result)

      attr_accessor collection_mode_class_names: Maintenance::CollectionMode::ClassNamesCollection

      attr_accessor hash_mode_class_names: Maintenance::HashMode::ClassNamesCollection

      attr_accessor input_option_helpers: Maintenance::Attributes::OptionHelpersCollection

      attr_accessor internal_option_helpers: Maintenance::Attributes::OptionHelpersCollection

      attr_accessor output_option_helpers: Maintenance::Attributes::OptionHelpersCollection

      attr_accessor action_aliases: Actions::Aliases::Collection

      attr_accessor action_shortcuts: Actions::Shortcuts::Collection

      attr_accessor action_rescue_handlers: Actions::RescueHandlers::Collection

      attr_accessor i18n_root_key: (Symbol | String)

      attr_accessor predicate_methods_enabled: bool

      def initialize: () -> void

      def predicate_methods_enabled?: -> bool

      private

      def default_collection_mode_class_names: -> Set[Class]

      def default_hash_mode_class_names: -> Set[Class]

      def default_input_option_helpers: -> Set[Maintenance::Attributes::OptionHelper]
    end
  end
end
