module Servactory
  module Configuration
    class Setup
      attr_accessor input_error_class: singleton(Servactory::Errors::InputError)

      attr_accessor internal_error_class: singleton(Servactory::Errors::InternalError)

      attr_accessor output_error_class: singleton(Servactory::Errors::OutputError)

      attr_accessor failure_class: singleton(Servactory::Errors::Failure)

      attr_accessor input_option_helpers: Servactory::Inputs::OptionHelpersCollection

      attr_accessor aliases_for_make: Methods::AliasesForMake::Collection

      attr_accessor shortcuts_for_make: Methods::Shortcuts::Collection

      def initialize: () -> void

      private

      def default_input_option_helpers: -> Set[Inputs::OptionHelper]
    end
  end
end
