module Servactory
  module Maintenance
    module Validations
      class ObjectSchema
        RESERVED_ATTRIBUTES: Array[Symbol]

        attr_reader errors: Array[Hash[Symbol, untyped]]

        @object: Hash[Symbol, untyped]
        @schema: Hash[Symbol, untyped]

        def self.validate: (*untyped) ?{ () -> untyped } -> self

        def initialize: (object: Hash[Symbol, untyped], schema: Hash[Symbol, untyped]) -> void

        def validate: () -> self

        def valid?: () -> bool

        private

        def validate_for: (object: Hash[Symbol, untyped], schema: Hash[Symbol, untyped], ?root_schema_key: Symbol?) -> void

        def validate_with: (object: Hash[Symbol, untyped], schema_key: Symbol, schema_value: Hash[Symbol, untyped], attribute_type: Class, attribute_required: bool) -> bool

        def should_be_checked_for?: (object: Hash[Symbol, untyped], schema_key: Symbol, schema_value: Hash[Symbol, untyped], required: bool) -> bool

        def prepare_value_from: (schema_value: Hash[Symbol, untyped], value: untyped, required: bool) -> untyped

        def fetch_default_from: (Hash[Symbol, untyped] value) -> untyped

        def add_error: (key_name: Symbol, expected_type: String, given_type: String) -> Array[Hash[Symbol, String]]
      end
    end
  end
end
