module Servactory
  module Maintenance
    module Validations
      class Performer
        @context: instance
        @attribute: (Inputs::Input | Internals::Internal | Outputs::Output)
        @value: untyped
        @validation_classes: Array[Class]
        @first_error: String?

        def self.validate!: (*untyped) ?{ () -> untyped } -> void

        def initialize: (context: instance, attribute: (Inputs::Input | Internals::Internal | Outputs::Output), value: untyped) -> void

        def validate!: () -> void

        private

        def process: -> void

        def process_option: (Symbol check_key, Hash[Symbol, untyped] check_options) -> void

        def process_validation_class: (validation_class: Class, check_key: Symbol, check_options: Hash[Symbol, untyped]) -> String?

        def validation_classes: -> Array[Class]

        def raise_errors: () -> void
      end
    end
  end
end
