module Servactory
  module Maintenance
    module Validations
      class Types
        @context: Servactory::Context::Workspace
        @attribute: (Servactory::Inputs::Input | Servactory::Internals::Internal | Servactory::Outputs::Output)
        @types: Array[Class]
        @value: untyped
        @error_callback: Proc
        @prepared_types: Array[Class]

        def self.validate!: (
          context: Servactory::Context::Workspace,
          attribute: (Servactory::Inputs::Input | Servactory::Internals::Internal | Servactory::Outputs::Output),
          types: Array[Class],
          value: untyped,
          error_callback: Proc
        ) -> void

        def initialize: (
          context: Servactory::Context::Workspace,
          attribute: (Servactory::Inputs::Input | Servactory::Internals::Internal | Servactory::Outputs::Output),
          types: Array[Class],
          value: untyped,
          error_callback: Proc
        ) -> void

        def validate!: () -> void

        private

        def prepared_types: () -> Array[Class]

        def prepared_types_from: (Array[Class] types) -> Array[Class]
      end
    end
  end
end
