module Servactory
  module InputAttributes
    module Tools
      class Check
        @context: instance
        @incoming_attributes: untyped
        @collection_of_input_attributes: Collection

        def self.check!: (*untyped) ?{ () -> untyped } -> void

        def initialize: (instance context, untyped incoming_attributes, Collection collection_of_input_attributes) -> void

        def check!: () -> void

        private

        attr_reader errors: CheckErrors

        def process_input: (InputAttribute input) -> void

        def process_option: (Symbol check_key, Hash[Symbol, untyped] check_options, input: InputAttribute) -> void

        def process_check_class: (Class check_class, input: InputAttribute, check_key: Symbol, check_options: Hash[Symbol, untyped]) -> instance

        def check_classes_from: (InputAttribute input) -> Array[Class]

        def errors: -> CheckErrors

        def raise_errors: () -> void
      end
    end
  end
end
