module Servactory
  module InputAttributes
    module Tools
      class FindUnnecessary
        @collection_of_input_attributes: Collection
        @context: instance

        @incoming_attributes: untyped

        @unnecessary_attributes: Array[Symbol]

        def self.check!: (*untyped) ?{ () -> untyped } -> void

        def initialize: (instance context, untyped incoming_attributes, Collection collection_of_input_attributes) -> void

        def check!: () -> void

        private

        def unnecessary_attributes: () -> Array[Symbol]
      end
    end
  end
end
