module Servactory
  module InputAttributes
    module Tools
      class Rules
        @collection_of_input_attributes: InputAttributes
        @context: instance

        def self.check!: (*untyped) ?{ () -> void } -> void

        def initialize: (instance context, InputAttributes collection_of_input_attributes) -> void

        def check!: () -> void

        private

        def check_for!: (InputAttribute input_attribute) -> void

        def raise_error_for: (InputAttribute input_attribute) -> void
      end
    end
  end
end
